// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarGenerationApi.Data;

#nullable disable

namespace SolarGenerationApi.Migrations
{
    [DbContext(typeof(SolarGenerationDbContext))]
    [Migration("20261007144659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarGenerationApi.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.GenerationReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CumulativeEnergyKwh")
                        .HasColumnType("float");

                    b.Property<double>("InstantaneousPowerKw")
                        .HasColumnType("float");

                    b.Property<int>("SolarInstallationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("Voltage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SolarInstallationId", "Timestamp")
                        .IsUnique();

                    b.ToTable("GenerationReadings");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.GridSubstation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DistrictId");

                    b.ToTable("GridSubstations");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.SolarInstallation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CapacityKw")
                        .HasColumnType("float");

                    b.Property<string>("DeviceSecretHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GridSubstationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InstalledOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeterIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GridSubstationId");

                    b.HasIndex("MeterIdentifier")
                        .IsUnique();

                    b.ToTable("SolarInstallations");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.District", b =>
                {
                    b.HasOne("SolarGenerationApi.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.GenerationReading", b =>
                {
                    b.HasOne("SolarGenerationApi.Models.SolarInstallation", "SolarInstallation")
                        .WithMany("GenerationReadings")
                        .HasForeignKey("SolarInstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarInstallation");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.GridSubstation", b =>
                {
                    b.HasOne("SolarGenerationApi.Models.District", "District")
                        .WithMany("GridSubstations")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.SolarInstallation", b =>
                {
                    b.HasOne("SolarGenerationApi.Models.GridSubstation", "GridSubstation")
                        .WithMany("SolarInstallations")
                        .HasForeignKey("GridSubstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GridSubstation");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.User", b =>
                {
                    b.HasOne("SolarGenerationApi.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolarGenerationApi.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.District", b =>
                {
                    b.Navigation("GridSubstations");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.GridSubstation", b =>
                {
                    b.Navigation("SolarInstallations");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("SolarGenerationApi.Models.SolarInstallation", b =>
                {
                    b.Navigation("GenerationReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
